feature/#2
ArtLesUe/czysty-kod-projekt-zaliczeniowy pull request #31
Opened 2022-11-11 10:53 UTC by ArtLesUe

Proszę o zaopiniowanie modelu użytkownika i tworzenia struktury bazy danych do niego.

Closes #2

2022-11-15 20:35 UTC, Weronika321 requested changes
Dodałam kilka komentarzy z propozycją poprawy

2022-11-15 20:35 UTC, Weronika321 commented on CkpTodoApp/Program.cs
> +DatabaseManagerController databaseManagerController = new DatabaseManagerController();
może powinniśmy używać niejawnego typowania jeśli nie zmienia to czytelności kodu?

2022-11-15 20:35 UTC, Weronika321 commented on CkpTodoApp/Interfaces/DatabaseManagerInterface.cs
> +  public interface IDatabaseManagerInterface
może powinniśmy konsekwentnie nazywać plik tak samo jak interfejs, w nim zawarty?

2022-11-15 20:35 UTC, Weronika321 commented on CkpTodoApp/Interfaces/DatabaseManagerInterface.cs
> +  public interface IDatabaseManagerInterface
Zastanawiam się czy nie lepiej gdybyśmy zmienili sposób rozmieszczenia plików. Możemy łatwo zobaczyć, że mamy doczynienia z interfejsem nawet jeśli nie umieścimy go w folderze "Interfaces", może lepiej umieścić interfejs blisko pliku   z klasą, która go implementuje?

2022-11-15 20:35 UTC, Weronika321 commented on CkpTodoApp/Models/ApiUserModel.cs
> +    public int Id { get; set; }
potrzebujemy używać wszystkich pól jako publiczne? może 'private set'?

2022-11-15 20:35 UTC, Weronika321 commented on CkpTodoApp/DatabaseControllers/DatabaseManagerController.cs
> +      string appFolder = folder != null ? folder : Environment.CurrentDirectory;
string appFolder = folder ?? Environment.CurrentDirectory;

2022-11-15 20:35 UTC, Weronika321 commented on CkpTodoApp/DatabaseControllers/DatabaseManagerController.cs
> +    public void InitDatabase()
public void InitDatabase() => ExecuteSQL("");

2022-11-15 21:00 UTC, Weronika321 commented on CkpTodoApp/DatabaseControllers/DatabaseManagerController.cs
> +    public DatabaseManagerController() { }
niepotrzebny konstruktor

2022-11-17 19:11 UTC, lorak0123 commented on CkpTodoApp/Interfaces/DatabaseManagerInterface.cs
> +  public interface IDatabaseManagerInterface
Nie jestem specjalistą, ale w jak przeglądałem dokumentację, to gdzieś mi się omknęło, że interfejs o nazwie Interfejs nazywał się IInterfejs.

2022-11-19 10:20 UTC, ArtLesUe commented on CkpTodoApp/DatabaseControllers/DatabaseManagerController.cs
> +    public DatabaseManagerController() { }
Został utworzony odpowiedni issue (#34) w tej sprawie, zamykam.

2022-11-19 10:24 UTC, ArtLesUe commented on CkpTodoApp/DatabaseControllers/DatabaseManagerController.cs
> +    public void InitDatabase()
Został utworzony ticket #35 w tej sprawie. Zamykam.

2022-11-19 10:27 UTC, ArtLesUe commented on CkpTodoApp/DatabaseControllers/DatabaseManagerController.cs
> +      string appFolder = folder != null ? folder : Environment.CurrentDirectory;
Został utworzony nowy ticket #36. Zamykam.

2022-11-19 10:28 UTC, ArtLesUe commented on CkpTodoApp/Models/ApiUserModel.cs
> +    public int Id { get; set; }
Tak, bo te pola muszą być pobierane przez API w widoku profilu. Jak zrobisz je prywatne, to API nie będzie ich zwracać podczas wywołania endpointa z użytkownikiem.

2022-11-19 10:30 UTC, ArtLesUe commented on CkpTodoApp/Interfaces/DatabaseManagerInterface.cs
> +  public interface IDatabaseManagerInterface
Utworzono ticket #37, zamykam.

2022-11-19 10:31 UTC, ArtLesUe commented on CkpTodoApp/Program.cs
> +DatabaseManagerController databaseManagerController = new DatabaseManagerController();
Nie wiem, to jest kwestia do dogadania, ja tam lubię jak mi kompilator pilnuje czy dobre klasy implementuję.

2022-11-19 10:31 UTC, ArtLesUe commented on CkpTodoApp/Interfaces/DatabaseManagerInterface.cs
> +  public interface IDatabaseManagerInterface
Zostanie to poprawione, utworzyłem ticker #37 w tej sprawie.

2022-11-19 10:43 UTC, Weronika321 approved these changes
Wspomniane w komentarzach poprawki zostaną wprowadzone na późniejszym etapie projektu.

2022-11-19 16:15 UTC, lorak0123 approved these changes
Jestem za mergem. Jak coś jeszcze będzie trzeba poprawić, to się to zrobi, a na razie odblokujemy dalsze prace.

2022-11-19 19:14 UTC, ToJanus approved these changes
Wygląda w porządku

2022-11-21 07:50 UTC, merged