feature/#4
ArtLesUe/czysty-kod-projekt-zaliczeniowy pull request #33
Opened 2022-11-11 13:46 UTC by ArtLesUe

Proszę o zaopiniowanie endpointu do logowania się użytkownika poprzez wygenerowanie tokena.

Close #4

2022-11-17 17:36 UTC, pawelpiatek1707 approved these changes

2022-11-19 19:15 UTC, ToJanus approved these changes

2022-11-20 10:39 UTC, Weronika321 requested changes
dodałam kilka uwag

2022-11-20 10:39 UTC, Weronika321 commented on CkpTodoApp/Requests/UserLoginRequest.cs
> +      return Login != null &&
lepiej zastosować IsNullOrEmpty

2022-11-20 10:39 UTC, Weronika321 commented on CkpTodoApp/Requests/UserLoginRequest.cs
> +      if (userList == null) { return 0; }
te dwa warunki można połączyć stosując 'OR' w warunku

2022-11-20 11:52 UTC, ArtLesUe commented on CkpTodoApp/Requests/UserLoginRequest.cs
> +      return Login != null &&
Zostanie poprawione w issue #38. Zamykam.

2022-11-20 11:54 UTC, ArtLesUe commented on CkpTodoApp/Requests/UserLoginRequest.cs
> +      if (userList == null) { return 0; }
Zostanie naprawione w issue #39. Zamykam.

2022-11-20 12:01 UTC, Weronika321 approved these changes

2022-11-21 07:51 UTC, merged