feature/#20
ArtLesUe/czysty-kod-projekt-zaliczeniowy pull request #57
Opened 2022-11-27 02:41 UTC by ToJanus

2022-11-27 07:21 UTC, ArtLesUe requested changes
Znalazłem lukę bezpieczeństwa, proszę poprawić przed zatwierdzeniem.

2022-11-27 07:21 UTC, ArtLesUe commented on CkpTodoApp/Controllers/User/UserDetailsController.cs
> +            'PasswordHashed', PasswordHashed,
Nie pobieramy hasła z bazy danych i nie wyświetlamy go w endpoincie pod żadnym pozorem, to jest naruszenie bezpieczeństwa. Proszę to poprawić.

2022-11-27 10:08 UTC, Weronika321 requested changes
zatwierdzę, gdy będą rozwiązane wszystkie wątki z komentarzy

2022-11-27 10:08 UTC, Weronika321 commented on CkpTodoApp/Controllers/User/UserDetailsController.cs
> +    private readonly ILogger<UserDetailsController> _logger;
_logger nie jest nigdzie używany

2022-11-28 09:52 UTC, ArtLesUe commented on CkpTodoApp/Controllers/User/UserDetailsController.cs
> +            'PasswordHashed', PasswordHashed,
Naprawione.

2022-11-28 09:53 UTC, ArtLesUe commented on CkpTodoApp/Controllers/User/UserDetailsController.cs
> +    private readonly ILogger<UserDetailsController> _logger;
Na razie te loggery zostawmy, bo one są wszędzie, muszę sprawdzić czy one czegoś nie robią.

2022-11-28 09:54 UTC, ArtLesUe approved these changes
Zmiany wprowadzone, zatwierdzam.

2022-11-28 09:54 UTC, merged