feature/#21
ArtLesUe/czysty-kod-projekt-zaliczeniowy pull request #58
Opened 2022-11-27 03:13 UTC by ToJanus

2022-11-27 07:25 UTC, ArtLesUe requested changes
Wykryto luki bezpieczeństwa, proszę poprawić.

2022-11-27 07:25 UTC, ArtLesUe commented on CkpTodoApp/Controllers/User/UserDetailsController.cs
> +            'PasswordHashed', PasswordHashed,
Nie pobieramy hasła z bazy danych i nie przekazujemy w endpoincie. Proszę to poprawić, to jest luka bezpieczeństwa.

2022-11-27 10:11 UTC, Weronika321 requested changes
zatwierdzę gdy będą rozwiązane wątki z komentarzy

2022-11-27 10:11 UTC, Weronika321 commented on CkpTodoApp/Controllers/User/UserEditController.cs
> +        string.IsNullOrEmpty(userEditRequest.Name) ? oldUser.Name : userEditRequest.Name,
można to zapisać w prostszy sposób

2022-11-27 10:11 UTC, Weronika321 commented on CkpTodoApp/Controllers/User/UserEditController.cs
> +      _logger = logger;
nigdzie nie używany logger

2022-11-28 09:56 UTC, ArtLesUe commented on CkpTodoApp/Controllers/User/UserDetailsController.cs
> +            'PasswordHashed', PasswordHashed,
Naprawione.

2022-11-28 09:58 UTC, ArtLesUe commented on CkpTodoApp/Controllers/User/UserEditController.cs
> +        string.IsNullOrEmpty(userEditRequest.Name) ? oldUser.Name : userEditRequest.Name,
Optymalizacje zostawmy na koniec.

2022-11-28 09:59 UTC, ArtLesUe commented on CkpTodoApp/Controllers/User/UserEditController.cs
> +      _logger = logger;
Tak, jak wcześniej, usuniemy je za jednym zamachem, jak ustalimy czy rzeczywiście nie są do niczego potrzebne.

2022-11-28 09:59 UTC, ArtLesUe approved these changes
Zatwierdzam kod po zmianach.

2022-11-28 10:00 UTC, merged