feature/#22
ArtLesUe/czysty-kod-projekt-zaliczeniowy pull request #59
Opened 2022-11-27 03:26 UTC by ToJanus

2022-11-27 07:37 UTC, ArtLesUe requested changes
Kilka poprawek jest koniecznych. Proszę o wprowadzenie.

2022-11-27 07:37 UTC, ArtLesUe commented on CkpTodoApp/Controllers/User/UserDetailsController.cs
> +            'PasswordHashed', PasswordHashed,
Nie pobieramy hasła z bazy danych i nie wyświetlamy go jako wyniku odpowiedzi. Luka bezpieczeństwa, proszę poprawić.

2022-11-27 07:37 UTC, ArtLesUe commented on CkpTodoApp/Models/ApiUserModel.cs
> +    public void Edit()
Zmieniłbym nazwę funkcji na `Update()` funkcja `Edit()` w niektórych frameworkach odblokowuje model do edycji, co może mylić. Jeżeli możesz, to popraw to.

2022-11-27 07:37 UTC, ArtLesUe commented on CkpTodoApp/Controllers/User/UserPasswordController.cs
> +      user.PasswordChange(UserRegisterController.Md5(userPasswordRequest.Password));
Nigdzie nie widzę sprawdzenia, czy nowe hasło nie jest puste. Popraw to proszę.

2022-11-27 07:37 UTC, ArtLesUe commented on CkpTodoApp/Controllers/User/UserPasswordController.cs
> +      ApiUserModel user = new ApiUserModel(id);
Nie widzę sprawdzenia, czy użytkownik istnieje w bazie danych.

2022-11-27 07:37 UTC, ArtLesUe commented on CkpTodoApp/Controllers/User/UserEditController.cs
> +      ApiUserModel oldUser = new ApiUserModel(id);
Nigdzie nie zostało sprawdzone, czy użytkownik istnieje przed edycją.

2022-11-27 12:08 UTC, Weronika321 requested changes
approve będzie po wprowadzonych poprawkach

2022-11-27 12:08 UTC, Weronika321 commented on CkpTodoApp/Controllers/User/UserDetailsController.cs
> +
zbędny logger

2022-11-28 10:07 UTC, ArtLesUe commented on CkpTodoApp/Controllers/User/UserDetailsController.cs
> +            'PasswordHashed', PasswordHashed,
Naprawione.

2022-11-28 10:14 UTC, ArtLesUe commented on CkpTodoApp/Controllers/User/UserDetailsController.cs
> +
Na razie je zostawiamy do momentu ustalenia czy nie są potrzebne.

2022-11-28 10:19 UTC, ArtLesUe commented on CkpTodoApp/Controllers/User/UserEditController.cs
> +      ApiUserModel oldUser = new ApiUserModel(id);
Dodano sprawdzanie czy model istnieje przed edycją.

2022-11-28 10:23 UTC, ArtLesUe commented on CkpTodoApp/Models/ApiUserModel.cs
> +    public void Edit()
Nazwa funkcji została zmieniona.

2022-11-28 10:28 UTC, ArtLesUe commented on CkpTodoApp/Controllers/User/UserPasswordController.cs
> +      ApiUserModel user = new ApiUserModel(id);
Naprawione.

2022-11-28 10:30 UTC, ArtLesUe approved these changes
Zatwierdzam po zmianach.

2022-11-28 10:31 UTC, merged